### ISSUE TITLE
IntlMoneyParser fails to parse zero values

### ISSUE THREAD

**Issue by Zxurian** [moneyphp/money#364]
so it looks like this was fixed previously in #173 , however it looks like it's back.

Running just this basic code

```php
IntlMoneyParser->parse('$0.00');
```

results in 
```
======================================================================
   The application has thrown an exception!
======================================================================
 InvalidArgumentException
 Empty number is invalid
----------------------------------------------------------------------
/var/www/dev-hub/vendor/moneyphp/money/src/Number.php:34
#0 /var/www/dev-hub/vendor/moneyphp/money/src/Number.php(108): Money\Number->__construct('', '')
#1 /var/www/dev-hub/vendor/moneyphp/money/src/Money.php(60): Money\Number::fromString('')
#2 /var/www/dev-hub/vendor/moneyphp/money/src/Parser/IntlMoneyParser.php(89): Money\Money->__construct('', Object(Money\Currency))
#3 /var/www/dev-hub/module/Acquisitions/src/Acquisitions/BookQuest/Importers/Mozenda.php(76): Money\Parser\IntlMoneyParser->parse('$0.00')
```

I just added `if ($decimal == '') { $decimal = '0'; }` right before the return, for my purposes, but don't know if there's other things that have to be updated as well.

**Comment by frederikbosch** [comment]
@Zxurian Fixed again, this time with tests.
